### ISSUE TITLE
Demonstrate use of Python 3 virtualenvs over Python 2 ones

### ISSUE THREAD

**Issue by edwinbalani** [SRCF/docs#11]
**As** someone following the SRCF docs
**I want** to be making Python 3 virtualenvs
**So that** I'm not using an obsolete version of Python instead

We discovered in #10 that we are accidentally directing people to create Python 2 virtualenvs in our tutorials, rather than Python 3 ones.  (thanks @zabop for the report!)  This happens because the `virtualenv` script itself uses Python 2 (at least in older versions of Ubuntu e.g. 16.04 xenial).

**To do**:

- [ ] Go through the docs to see where use of the `virtualenv` command is instructed
- [ ] Make sure all references are updated to specify `virtualenv -p python3`, which cause the `virtualenv` script to use the binary providing the 'python3' command as the base on which to build the virtualenv

**Alternative approach**: instead update our instructions to use Python 3's built-in `venv` module, i.e. invocations of `python3 -m venv`.

**Comment by matiasilva** [comment]
Closed by f46b3556c1078fc82f63b20229966b448f5aa566. Thanks for reporting.
