### ISSUE TITLE
Fix incorrect chmod command in node tutorial

### ISSUE THREAD

**Issue by matiasilva** [SRCF/docs#22]
We ask users to chmod a file called "run" which should really be "run.sh"

**Comment by CHTJonas** [comment]
Are you referring to the following part of the tutorial? I feel like run scripts for applications like this are much more commonly stored without file extensions than with (take a look inside the `bin` directory of any RoR app or indeed at any of the scripts under `/usr/local/bin/srcf*`).

https://github.com/SRCF/docs/blob/da0e0dcab4d3084c504f9feb37f47e9b962989c8/source/learn/tutorials/deploy-node.rst#L66-L90

I think it would be much more beneficial to note somewhere that file extensions have little if any precedent on (server) Linux. I feel like that would be much more helpful to first-time users coming to us from Windows than simply adding `.sh` to all our tutorial scripts.

**Comment by matiasilva** [comment]
That's a good point, though my motivation was that a user reported that Django or whatever wouldn't accept a run scrpit without an extension. Check the email though, I may have misread.
