### ISSUE TITLE
Broken internal links in docs

### ISSUE THREAD

**Issue by cjs59** [SRCF/docs#41]
https://docs.srcf.net/reference/web-hosting/regular-hosting/ has a broken link to the WordPress tutorial

https://docs.srcf.net/reference/web-hosting/web-applications/ has a broken link in the "Routing traffic to your app" paragraph - looks like it might be a missing closing quote.

**Comment by matiasilva** [comment]
Hello! Thanks for bringing these issues to our attention. I've now fixed them in the latest commit. I hope you enjoy the new version of our docs! Any and all feedback is welcome, and you are also welcome to submit your own changes if interested.
