### ISSUE TITLE
Blocking access to xmlrpc.php should be included in Securing Wordpress and the sample wordpress .htaccess file

### ISSUE THREAD

**Issue by WJBarnes456** [SRCF/docs#53]
I was reading through https://docs.srcf.net/guides/websites/securing-wordpress/, as a university society I remain on good terms with is thinking of using WordPress as a CMS.

I noticed that neither this file, nor the sample htaccess file at `/public/societies/sample/public_html/wordpress/.htaccess`, advocates for restricting access to the `xmlrpc.php` file, which is [enabled by default](https://codex.wordpress.org/XML-RPC_Support), and [can be used to significantly amplify brute force attacks against the WordPress instance](https://blog.sucuri.net/2015/10/brute-force-amplification-attacks-against-wordpress-xmlrpc.html). This would make a weak admin password even easier to crack.

I suggest adding this to https://github.com/srcf/docs/blob/master/content/guides/websites/securing-wordpress.md and the reference .htaccess file (though I have no idea where that can be found!)

**Comment by WJBarnes456** [comment]
I'd open a PR to do this myself if it weren't so late - feel free to ping me if you're reading this message at a later date and I haven't opened one, I probably just forgot.

**Comment by WJBarnes456** [comment]
Thanks for the quick response! I'm glad to hear that's the case, I'm happy to close then.

**Comment by mas90** [comment]
I wonder whether it would be a good idea for the documentation to mention the block, both so that SRCF users know that we're handling that, and so that non-SRCF users who stumble upon our documentation know to do it?  Our documentation may be aimed at our own users, but this page in particular is more broadly relevant and may show up in Google searches.
